#!/bin/bash
set -e

export XDG_CONFIG_DIRS=/home/dataiku/workspace/user-versioned/settings/rstudio

# Initial config (ilk defa başlatılıyorsa ayarla)
if [ ! -d "/home/dataiku/workspace/user-versioned/settings/rstudio/rstudio" ]; then
    mkdir -p /home/dataiku/workspace/user-versioned/settings/rstudio/rstudio
    cat <<EOF > /home/dataiku/workspace/user-versioned/settings/rstudio/rstudio/rstudio-prefs.json
{
  "initial_working_directory": "/home/dataiku/workspace",
  "posix_terminal_shell": "bash"
}
EOF
fi

# R code env’leri ekle (varsa)
if [ -d "/opt/dataiku/r-code-envs" ]; then
  for i in $(ls -r /opt/dataiku/r-code-envs); do
    echo "Adding code env $i"
    export R_LIBS_USER="/opt/dataiku/r-code-envs/$i/R.lib:$R_LIBS_USER"
  done
fi

# Logging conf varsa bilgi ver
if [ -f "/home/dataiku/workspace/user-versioned/settings/rstudio/rstudio/logging.conf" ]; then
    echo "Logging configuration loaded from /home/dataiku/workspace/user-versioned/settings/rstudio/rstudio/logging.conf"
fi

# RStudio server’ı dataiku olarak başlat
exec /usr/lib/rstudio-server/bin/rserver \
    --server-daemonize=0 \
    --server-user=dataiku \
    --www-port=8787 \
    --www-address=0.0.0.0 \
    --auth-none=1
